name: replace_with_package_name
description: TBD
version: 0.0.0
homepage: https://github.com/neo-dart/replace_with_package_name

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.1

dev_dependencies:
  coverage: ^1.6.3
  neodart: ^0.1.2
  test: ^1.24.3
