name: Dart

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Presubmit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Run Presubmits
        run: make

      - name: Upload Coverage
        uses: codecov/codecov-action@v3.1.0
